import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { createPhase2ProfessionalCompositeFixture } from "./phase2-professional-composite-fixture";
import { normalizeAutoLayoutProjection, resolveCoreBatch } from "./transaction-batch";
import { wasmHydrationBatches } from "./wasm-hydration-batches";

type WasmRuntime = typeof import("../wasm/generated/editor_wasm");

let runtime: Promise<WasmRuntime> | undefined;

async function loadRuntime() {
  if (!runtime) {
    runtime = import("../wasm/generated/editor_wasm").then(async (wasm) => {
      // The browser Worker obtains this through Turbopack's static URL. Tests
      // provide the exact generated bytes explicitly because Node cannot fetch
      // a file: URL in wasm-bindgen's default initializer.
      await wasm.default({ module_or_path: await readFile(new URL("../wasm/generated/editor_wasm_bg.wasm", import.meta.url)) });
      return wasm;
    });
  }
  return runtime;
}

describe("F-PHASE2-PROFESSIONAL-COMPOSITE WASM hydration", () => {
  it("seeds the complete fixture through the same deferred-mask Core batch used by the browser Worker", async () => {
    const fixture = createPhase2ProfessionalCompositeFixture();
    const wasm = await loadRuntime();
    const engine = new wasm.DocumentEngine();
    engine.seed_assets_json(JSON.stringify(fixture.assets));
    const nodes = normalizeAutoLayoutProjection(fixture.nodes);

    for (const batchNodes of wasmHydrationBatches(nodes)) {
      const resolved = resolveCoreBatch([], batchNodes.map((node) => ({ type: "create" as const, node })));
      expect(resolved).toBeDefined();
      engine.seed_batch_json(JSON.stringify(resolved!.batch));
    }

    // Hydration must not manufacture a user transaction merely to restore a
    // deferred mask flag; the first user edit still begins at revision zero.
    expect(engine.revision).toBe(0n);
    const hydrated = JSON.parse(engine.snapshot_json()) as { nodes: Array<{ id: string; parentId?: string; kind: string; fill: string; isMask?: boolean }> };
    expect(hydrated.nodes).toHaveLength(fixture.nodes.length);
    const maskRunId = "00000000-0000-4000-8000-000000003023";
    expect(hydrated.nodes.filter((node) => node.parentId === maskRunId).map((node) => node.id)).toEqual([
      "00000000-0000-4000-8000-000000003009",
      "00000000-0000-4000-8000-000000003010",
    ]);
    expect(hydrated.nodes.find((node) => node.id === "00000000-0000-4000-8000-000000003009")).toMatchObject({ kind: "ellipse", fill: "#ffffff", isMask: true });
    expect(hydrated.nodes.find((node) => node.id === "00000000-0000-4000-8000-000000003010")).toMatchObject({ kind: "rectangle", fill: "#ec4899" });
    expect(hydrated.nodes.find((node) => node.id === "00000000-0000-4000-8000-000000003014")).toMatchObject({ kind: "booleanOperation" });
  });
});
