import { FigmaCompatibleRuntime } from "./figma-compatible-runtime";

/** Compile-only M1 public-surface probe. It keeps our facade's P0 calls aligned
 * with the locked Plugin API vocabulary while leaving commitAsync visibly in
 * the project-extension namespace. */
export function assertRuntimePublicContract(runtime: FigmaCompatibleRuntime): {
  rootId: string;
  nodeLookup: Promise<unknown>;
  acceptedRevision: Promise<number>;
} {
  void runtime.variables.getLocalVariablesAsync();
  void runtime.variables.getLocalVariableCollectionsAsync();
  void runtime.variables.getVariableByIdAsync("V:spacing");
  const component = runtime.createComponent();
  const propertyLayer = runtime.createRectangle();
  component.appendChild(propertyLayer);
  const propertyName = component.addComponentProperty("Enabled", "BOOLEAN", true);
  propertyLayer.componentPropertyReferences = { visible: propertyName };
  void propertyLayer.componentPropertyReferences;
  propertyLayer.componentPropertyReferences = null;
  const renamedProperty = component.editComponentProperty(propertyName, { name: "Active", defaultValue: false });
  component.deleteComponentProperty(renamedProperty);
  void component.key;
  void component.remote;
  const instance = component.createInstance();
  instance.setProperties({});
  const slot = component.createSlot();
  void slot.limitViolations;
  void slot.resetSlot;
  const clonedComponent = component.clone();
  void clonedComponent.id;
  const componentVariant = runtime.createComponent();
  const componentSet = runtime.combineAsVariants([component, componentVariant], runtime.currentPage);
  void componentSet.variantGroupProperties;
  void componentSet.componentPropertyDefinitions;
  void component.variantProperties;
  void instance.variantProperties;
  const variantPropertyName = componentSet.addComponentProperty("State", "VARIANT", "Default");
  componentSet.editComponentProperty(variantPropertyName, { name: "Mode" });
  instance.setProperties({ Mode: "Default" });
  const setPropertyName = componentSet.addComponentProperty("Label", "TEXT", "Continue");
  const renamedSetProperty = componentSet.editComponentProperty(setPropertyName, { name: "Title", defaultValue: "Save" });
  componentSet.deleteComponentProperty(renamedSetProperty);
  void slot.children;
  void instance.children;
  void instance.getMainComponentAsync();
  const componentSource = runtime.createFrame();
  componentSource.appendChild(runtime.createRectangle());
  const convertedComponent = runtime.createComponentFromNode(componentSource);
  instance.swapComponent(convertedComponent);
  const detachedInstance = instance.detachInstance();
  void detachedInstance.children;
  void convertedComponent.children;
  const slice = runtime.createSlice();
  slice.resize(320, 180);
  if (false) {
    const media = runtime.createGif("admitted-gif-hash");
    void media.mediaData.hash;
    void runtime.createLinkPreviewAsync("https://example.com");
  }
  const rectangle = runtime.createRectangle();
  const runtimeVariable = runtime.variables.getLocalVariables("FLOAT")[0];
  if (runtimeVariable) {
    runtimeVariable.setVariableCodeSyntax("WEB", "--spacing");
    runtimeVariable.removeVariableCodeSyntax("WEB");
    void runtimeVariable.codeSyntax.WEB;
    rectangle.setBoundVariable("opacity", runtimeVariable);
    rectangle.setBoundVariable("width", runtimeVariable);
    rectangle.setBoundVariable("cornerRadius", runtimeVariable);
  }
  void rectangle.cornerRadius;
  rectangle.topLeftRadius = rectangle.topLeftRadius;
  void rectangle.boundVariables;
  const runtimeCollection = runtime.variables.getLocalVariableCollections()[0];
  if (runtimeCollection) rectangle.setExplicitVariableModeForCollection(runtimeCollection, runtimeCollection.defaultModeId);
  void rectangle.explicitVariableModes;
  void rectangle.resolvedVariableModes;
  rectangle.fills = [{ type: "SOLID", color: { r: 1, g: 0, b: 0 }, opacity: .5, blendMode: "MULTIPLY" }];
  rectangle.strokes = [{
    type: "GRADIENT_LINEAR",
    gradientTransform: [[1, 0, 0], [0, 1, 0]],
    gradientStops: [{ position: 0, color: { r: 1, g: 1, b: 1, a: 1 } }, { position: 1, color: { r: 0, g: 0, b: 0, a: 1 } }],
  }];
  void rectangle.fills;
  void rectangle.strokes;
  rectangle.fillStyleId = "S:brand-fill";
  rectangle.strokeStyleId = "S:brand-stroke";
  if (false) void rectangle.setFillStyleIdAsync("S:brand-fill");
  if (false) void rectangle.setStrokeStyleIdAsync("S:brand-stroke");
  const text = runtime.createText();
  const runtimeStringVariable = runtime.variables.getLocalVariables("STRING")[0];
  if (runtimeStringVariable) text.setBoundVariable("characters", runtimeStringVariable);
  const runtimeColorVariable = runtime.variables.getLocalVariables("COLOR")[0];
  if (runtimeColorVariable) rectangle.fills = [runtime.variables.setBoundVariableForPaint({ type: "SOLID", color: { r: 1, g: 0, b: 0 } }, "color", runtimeColorVariable)];
  if (runtimeColorVariable) rectangle.strokes = [{ type: "GRADIENT_LINEAR", gradientTransform: [[1, 0, 0], [0, 1, 0]], gradientStops: [{ position: 0, color: { r: 1, g: 0, b: 0, a: 1 }, boundVariables: { color: runtime.variables.createVariableAlias(runtimeColorVariable) } }, { position: 1, color: { r: 0, g: 0, b: 1, a: 1 } }] }];
  if (runtimeVariable) rectangle.effects = [runtime.variables.setBoundVariableForEffect({ type: "LAYER_BLUR", radius: 4, visible: true, blurType: "NORMAL" }, "radius", runtimeVariable)];
  text.textAutoResize = "HEIGHT";
  text.textTruncation = "ENDING";
  text.maxLines = 2;
  void text.textTruncation;
  void text.maxLines;
  text.insertCharacters(0, "A", "AFTER");
  text.setRangeFontSize(0, 1, 16);
  text.letterSpacing = { value: 1, unit: "PIXELS" };
  void text.getRangeLetterSpacing(0, 1);
  text.setRangeLetterSpacing(0, 1, { value: -0.25, unit: "PIXELS" });
  void text.hasMissingFont;
  text.fontSize = 16;
  void text.fontSize;
  void text.fontWeight;
  void text.getRangeFontSize(0, 1);
  void text.getRangeFontWeight(0, 1);
  void text.openTypeFeatures;
  void text.getRangeOpenTypeFeatures(0, 1);
  void text.textStyleId;
  void text.getRangeTextStyleId(0, 1);
  text.textStyleId = "S:body";
  if (false) void text.setTextStyleIdAsync("S:body");
  void text.fillStyleId;
  void text.getRangeFillStyleId(0, 1);
  text.fillStyleId = "S:brand-fill";
  if (false) void text.setFillStyleIdAsync("S:brand-fill");
  text.setRangeFillStyleId(0, 1, "S:brand-fill");
  if (false) void text.setRangeFillStyleIdAsync(0, 1, "S:brand-fill");
  text.setRangeTextStyleId(0, 1, "S:body");
  if (false) void text.setRangeTextStyleIdAsync(0, 1, "S:body");
  void text.fontName;
  void text.getRangeFontName(0, 1);
  void text.getRangeAllFontNames(0, 1);
  text.setRangeFontName(0, 1, { family: "Inter", style: "Regular" });
  text.textCase = "UPPER";
  void text.getRangeTextCase(0, 1);
  text.setRangeTextCase(0, 1, "TITLE");
  text.textDecoration = "UNDERLINE";
  void text.getRangeTextDecoration(0, 1);
  text.setRangeTextDecoration(0, 1, "STRIKETHROUGH");
  text.textDecorationStyle = "WAVY";
  void text.getRangeTextDecorationStyle(0, 1);
  text.setRangeTextDecorationStyle(0, 1, "DOTTED");
  void text.textDecorationOffset;
  text.textDecorationOffset = { unit: "AUTO" };
  void text.getRangeTextDecorationOffset(0, 1);
  text.setRangeTextDecorationOffset(0, 1, { value: 10, unit: "PERCENT" });
  void text.textDecorationThickness;
  text.textDecorationThickness = { unit: "AUTO" };
  void text.getRangeTextDecorationThickness(0, 1);
  text.setRangeTextDecorationThickness(0, 1, { value: 2, unit: "PIXELS" });
  void text.textDecorationColor;
  text.textDecorationColor = { value: "AUTO" };
  void text.getRangeTextDecorationColor(0, 1);
  text.setRangeTextDecorationColor(0, 1, { value: { type: "SOLID", color: { r: 1, g: 0, b: 0 }, opacity: .5 } });
  text.textWrapStyle = "BALANCE";
  void text.textWrapStyle;
  void text.getRangeTextWrapStyle(0, 1);
  text.setRangeTextWrapStyle(0, 1, "PRETTY");
  void text.textDecorationSkipInk;
  text.textDecorationSkipInk = true;
  void text.leadingTrim;
  text.leadingTrim = "CAP_HEIGHT";
  void text.getRangeListOptions(0, text.characters.length);
  text.setRangeListOptions(0, text.characters.length, { type: "UNORDERED" });
  text.paragraphSpacing = 8;
  void text.paragraphSpacing;
  void text.getRangeParagraphSpacing(0, text.characters.length);
  text.setRangeParagraphSpacing(0, text.characters.length, 10);
  text.paragraphIndent = 12;
  void text.paragraphIndent;
  void text.getRangeParagraphIndent(0, text.characters.length);
  text.setRangeParagraphIndent(0, text.characters.length, 14);
  text.listSpacing = 6;
  void text.listSpacing;
  text.hangingList = true;
  void text.hangingList;
  text.hangingPunctuation = true;
  void text.hangingPunctuation;
  void text.getRangeListSpacing(0, text.characters.length);
  text.setRangeListSpacing(0, text.characters.length, 8);
  void text.getRangeIndentation(0, text.characters.length);
  text.setRangeIndentation(0, text.characters.length, 2);
  void text.getRangeTextDecorationSkipInk(0, 1);
  text.setRangeTextDecorationSkipInk(0, 1, false);
  text.hyperlink = { type: "URL", value: "https://example.com" };
  void text.getRangeHyperlink(0, 1);
  text.setRangeHyperlink(0, 1, { type: "NODE", value: "1:2" });
  text.setRangeFills(0, 1, [{ type: "SOLID", color: { r: 1, g: 0, b: 0 }, opacity: .5 }]);
  void text.getRangeFills(0, 1);
  void text.getStyledTextSegments(["fontName", "fontSize", "fontWeight", "fontStyle", "textCase", "lineHeight", "fills", "listOptions", "listSpacing", "indentation", "paragraphIndent", "paragraphSpacing", "textWrapStyle", "hyperlink"]);
  text.deleteCharacters(0, 1);
  const polygon = runtime.createPolygon();
  polygon.pointCount = polygon.pointCount;
  const star = runtime.createStar();
  star.innerRadius = star.innerRadius;
  const vector = runtime.createVector();
  vector.vectorPaths = [{ windingRule: "EVENODD", data: "M 0 0 L 100 100 L 0 100 L 100 0 Z" }];
  const vectorNetwork = vector.vectorNetwork;
  void vectorNetwork.vertices;
  void vectorNetwork.segments;
  if (false) void vector.setVectorNetworkAsync({
    vertices: [{ x: 0, y: 0, strokeCap: "ROUND" }, { x: 100, y: 0, strokeCap: "ARROW_LINES" }],
    segments: [{ start: 0, end: 1 }],
  });
  vector.strokeWeight = 3;
  const initialStrokeCap = vector.strokeCap;
  if (initialStrokeCap !== runtime.mixed) vector.strokeCap = initialStrokeCap;
  vector.strokeCap = "ROUND";
  vector.strokeJoin = "BEVEL";
  vector.strokeMiterLimit = 4;
  vector.dashPattern = [8, 4];
  const vectorOperand = runtime.createVector();
  const boolean = runtime.union([vector, vectorOperand], runtime.currentPage);
  boolean.booleanOperation = "EXCLUDE";
  if (false) void runtime.flatten([boolean]);
  rectangle.x = rectangle.x;
  rectangle.y = rectangle.y;
  rectangle.name = rectangle.name;
  rectangle.opacity = rectangle.opacity;
  rectangle.resize(rectangle.width, rectangle.height);
  const frame = runtime.createFrame();
  frame.layoutMode = "HORIZONTAL";
  frame.primaryAxisSizingMode = "FIXED";
  frame.counterAxisSizingMode = "FIXED";
  frame.primaryAxisAlignItems = "SPACE_BETWEEN";
  frame.counterAxisAlignItems = "BASELINE";
  frame.minWidth = 120;
  frame.maxWidth = 640;
  frame.strokeTopWeight = 1;
  frame.strokeRightWeight = 2;
  frame.strokeBottomWeight = 3;
  frame.strokeLeftWeight = 4;
  frame.appendChild(rectangle);
  if (runtimeVariable) {
    frame.setBoundVariable("itemSpacing", runtimeVariable);
    frame.setBoundVariable("paddingLeft", runtimeVariable);
    frame.setBoundVariable("strokeTopWeight", runtimeVariable);
    rectangle.setBoundVariable("minWidth", runtimeVariable);
  }
  if (false) void runtime.flatten([boolean], frame, 0);
  rectangle.layoutSizingHorizontal = "FILL";
  rectangle.layoutSizingVertical = "FIXED";
  rectangle.layoutPositioning = "AUTO";
  rectangle.layoutAlign = "CENTER";
  rectangle.constraints = { horizontal: "STRETCH", vertical: "CENTER" };
  const wrapFrame = runtime.createFrame();
  wrapFrame.layoutMode = "HORIZONTAL";
  wrapFrame.layoutWrap = "WRAP";
  wrapFrame.counterAxisSpacing = 12;
  if (runtimeVariable) wrapFrame.setBoundVariable("counterAxisSpacing", runtimeVariable);
  wrapFrame.counterAxisAlignContent = "SPACE_BETWEEN";
  const connector = runtime.createConnector();
  connector.connectorLineType = "ELBOWED";
  connector.reconnect({ position: { x: 0, y: 0 } }, { position: { x: 200, y: 80 } });
  connector.connectorText = "Review";
  const shapeWithText = runtime.createShapeWithText();
  shapeWithText.shapeType = "DIAMOND";
  shapeWithText.text.characters = "Approve";
  shapeWithText.text.fontSize = 18;
  void shapeWithText.text.hasMissingFont;
  void shapeWithText.text.fontWeight;
  void shapeWithText.text.getRangeFontSize(0, 7);
  void shapeWithText.text.getRangeFontWeight(0, 7);
  void shapeWithText.text.openTypeFeatures;
  void shapeWithText.text.getRangeOpenTypeFeatures(0, 7);
  void shapeWithText.text.fontName;
  void shapeWithText.text.getRangeFontName(0, 7);
  void shapeWithText.text.getRangeAllFontNames(0, 7);
  shapeWithText.text.setRangeFontName(0, 7, { family: "Inter", style: "Regular" });
  shapeWithText.text.textCase = "SMALL_CAPS";
  void shapeWithText.text.getRangeTextCase(0, 7);
  shapeWithText.text.setRangeTextCase(0, 7, "SMALL_CAPS_FORCED");
  shapeWithText.text.textDecoration = "UNDERLINE";
  void shapeWithText.text.getRangeTextDecoration(0, 7);
  shapeWithText.text.setRangeTextDecoration(0, 7, "NONE");
  shapeWithText.text.textDecorationStyle = "SOLID";
  void shapeWithText.text.getRangeTextDecorationStyle(0, 7);
  shapeWithText.text.setRangeTextDecorationStyle(0, 7, "WAVY");
  void shapeWithText.text.textDecorationOffset;
  shapeWithText.text.textDecorationOffset = { value: 2, unit: "PIXELS" };
  void shapeWithText.text.getRangeTextDecorationOffset(0, 7);
  shapeWithText.text.setRangeTextDecorationOffset(0, 7, { unit: "AUTO" });
  void shapeWithText.text.textDecorationThickness;
  shapeWithText.text.textDecorationThickness = { value: 8, unit: "PERCENT" };
  void shapeWithText.text.getRangeTextDecorationThickness(0, 7);
  shapeWithText.text.setRangeTextDecorationThickness(0, 7, { unit: "AUTO" });
  void shapeWithText.text.textDecorationColor;
  shapeWithText.text.textDecorationColor = { value: "AUTO" };
  void shapeWithText.text.getRangeTextDecorationColor(0, 7);
  shapeWithText.text.setRangeTextDecorationColor(0, 7, { value: { type: "SOLID", color: { r: 0, g: .5, b: 1 }, opacity: .75 } });
  void shapeWithText.text.textDecorationSkipInk;
  shapeWithText.text.textDecorationSkipInk = true;
  void shapeWithText.text.leadingTrim;
  shapeWithText.text.leadingTrim = "CAP_HEIGHT";
  void shapeWithText.text.getRangeListOptions(0, shapeWithText.text.characters.length);
  shapeWithText.text.setRangeListOptions(0, shapeWithText.text.characters.length, { type: "UNORDERED" });
  shapeWithText.text.listSpacing = 6;
  void shapeWithText.text.listSpacing;
  shapeWithText.text.hangingList = true;
  void shapeWithText.text.hangingList;
  shapeWithText.text.hangingPunctuation = true;
  void shapeWithText.text.hangingPunctuation;
  void shapeWithText.text.getRangeListSpacing(0, shapeWithText.text.characters.length);
  shapeWithText.text.setRangeListSpacing(0, shapeWithText.text.characters.length, 8);
  void shapeWithText.text.getRangeIndentation(0, shapeWithText.text.characters.length);
  shapeWithText.text.setRangeIndentation(0, shapeWithText.text.characters.length, 2);
  void shapeWithText.text.getRangeTextDecorationSkipInk(0, 7);
  shapeWithText.text.setRangeTextDecorationSkipInk(0, 7, false);
  shapeWithText.text.hyperlink = { type: "URL", value: "https://example.com" };
  void shapeWithText.text.getRangeHyperlink(0, 7);
  shapeWithText.text.setRangeHyperlink(0, 7, null);
  shapeWithText.text.setRangeLetterSpacing(0, 7, { value: 1, unit: "PIXELS" });
  shapeWithText.text.lineHeight = { value: 24, unit: "PIXELS" };
  shapeWithText.text.lineHeight = { value: 125, unit: "PERCENT" };
  shapeWithText.text.lineHeight = { unit: "AUTO" };
  void shapeWithText.text.lineHeight;
  shapeWithText.text.paragraphSpacing = 8;
  void shapeWithText.text.paragraphSpacing;
  shapeWithText.text.paragraphIndent = 12;
  void shapeWithText.text.paragraphIndent;
  shapeWithText.text.textWrapStyle = "BALANCE";
  void shapeWithText.text.textWrapStyle;
  void shapeWithText.text.getRangeLineHeight(0, 7);
  shapeWithText.text.setRangeLineHeight(0, 7, { value: 26, unit: "PIXELS" });
  shapeWithText.text.setRangeLineHeight(0, 7, { value: 150, unit: "PERCENT" });
  void shapeWithText.text.getRangeParagraphSpacing(0, 7);
  shapeWithText.text.setRangeParagraphSpacing(0, 7, 10);
  void shapeWithText.text.getRangeParagraphIndent(0, 7);
  shapeWithText.text.setRangeParagraphIndent(0, 7, 14);
  void shapeWithText.text.getRangeTextWrapStyle(0, 7);
  shapeWithText.text.setRangeTextWrapStyle(0, 7, "PRETTY");
  shapeWithText.text.fills = [{ type: "SOLID", color: { r: 0, g: 0, b: 1 } }];
  shapeWithText.text.fillStyleId = "S:brand-fill";
  if (false) void shapeWithText.text.setFillStyleIdAsync("S:brand-fill");
  void shapeWithText.text.getRangeFillStyleId(0, 7);
  shapeWithText.text.setRangeFillStyleId(0, 7, "S:brand-fill");
  if (false) void shapeWithText.text.setRangeFillStyleIdAsync(0, 7, "S:brand-fill");
  shapeWithText.text.setRangeFills(0, 7, [{ type: "SOLID", color: { r: 1, g: 0, b: 0 }, opacity: .5 }]);
  void shapeWithText.text.getRangeFills(0, 7);
  void shapeWithText.text.getStyledTextSegments(["fontSize", "fontStyle", "paragraphSpacing", "textWrapStyle"], 0, 7);
  shapeWithText.text.insertCharacters(7, "d", "AFTER");
  const textPathSource = runtime.createVector();
  textPathSource.vectorPaths = [{ windingRule: "NONE", data: "M 0 60 C 40 0 120 0 160 60" }];
  const textPath = runtime.createTextPath(textPathSource, 0, .25);
  textPath.characters = "Along the curve";
  textPath.textAlignHorizontal = "CENTER";
  textPath.textAlignVertical = "TOP";
  textPath.autoRename = false;
  const repeatSourceA = runtime.createRectangle();
  const repeatSourceB = runtime.createEllipse();
  const transformGroup = runtime.transformGroup(
    [repeatSourceA, repeatSourceB],
    runtime.currentPage,
    0,
    [{ type: "REPEAT", repeatType: "LINEAR", count: 2, unitType: "PIXELS", offset: 120, axis: "HORIZONTAL" }],
  );
  transformGroup.transformModifiers = transformGroup.transformModifiers;
  transformGroup.transformModifiers = [{ type: "REPEAT", repeatType: "RADIAL", count: 5, unitType: "PIXELS", offset: 64 }];
  transformGroup.transformModifiers = [
    { type: "REPEAT", repeatType: "LINEAR", count: 1, unitType: "PIXELS", offset: 120, axis: "HORIZONTAL" },
    { type: "REPEAT", repeatType: "RADIAL", count: 3, unitType: "PIXELS", offset: 64 },
  ];
  runtime.currentPage.appendChild(frame);
  return {
    rootId: runtime.root.id,
    nodeLookup: runtime.getNodeByIdAsync(rectangle.id),
    acceptedRevision: runtime.commitAsync(),
  };
}
